# Site settings
title: Rishabh Karajgi's CV 
description: karajrish's CV
favicon: /resumecard/assets/img/avatar.jpg
baseurl: ""
url: ""
rss_url: 
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Rishabh Karajgi
  title: Developer and Programmer
  address: Warangal, India
  email: rishabh.karajgi@gmail.com
  link: 
  weibo:
  github: karajrish
  linkedin: rishabh-karajgi-b450036b
  twitter: RishabhKarajgi
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: WSDC, NIT Warangal
      location: Warangal, India
      title: Web Designer and Developer
      started: 2014
      duration: (2014 - 2015)
      description: "Design, develop and extend maintenance services for software and websites to fulfill the IT needs of the institution. This Cell coordinates with the ITSCC (IT Services Coordination Committee) of the institute for deploying IT services.
        <ul>
          <li>College Website (www.nitw.ac.in)</li>
          <li>Student Registration</li>
          <li>Online Mess and Hostel Allotment</li>
          <li>Alumni onboarding request automation</li>
          </ul>" 
  educationHistory:
    - education1:
      organization: Indian School Of Business
      location: Hyderabad, India
      degree: Masters
      major: Technology Entrepreneurship
      started: 2015
      duration: (2015 - 2017)
      description: "A program that provides guidance and support to develop own's own product / service and launch their own technical venture and provide opportunities to build robust partnerships with corporates and government agencies"
    - education2:
      organization: National Institute of Technology, Warangal
      location: Warangal, India
      degree: B.Tech
      major: Computer Science and Engineering
      started: 2013
      duration: (2013 - 2017)
      description: "Ranked amongst the top 15 institutions of the country and amongst top 10 in Computer Science.
      Activities undertaken:
      <ul>
      <li>Additional Secretary of Quiz Club</li>
      <li>Founded Q-Factor - One of the largest inter-college quizzing festivals of the state</li>
      <li>IEEE Student body member</li>
      <li>Web Developer at WSDC</li>
      <li>Varsity Tennis team</li></ul>"
    - education3:
      organization: Indian School Muscat
      location: Muscat, Oman
      degree: High School
      major: CBSE
      started: 2001
      duration: (2001 - 2013)
      description: "
      Academics:
      <ul>
      <li>All India CBSE class X Examinations : 10/10 CGPA</li>
      <li>All India CBSE class XII Examinations : 91%</li></ul>
      Extra-curriculars:
        <ul>
        <li>Student council member : Public Relations Coordinator </li>
        <li>Sports : Tennis, Table-tennis, Basketball</li>
        <li> Active participation and accolades in quizzing, debates, dramatics</li></ul>
        "
  languages:
    - language1:
      name: Marathi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML/CSS
      percentage: 100%
    - skill2:
      name: JavaScript
      percentage: 70%
    - skill3:
      name: C/C++
      percentage: 70%
    - skill4:
      name: Python
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
  Frameworks:
    - skill1:
      name: Django Python
      percentage: 70%
    - skill2:
      name: Bootstrap CSS
      percentage: 90%
    - skill3:
      name: CodeIgniter PHP
      percentage: 60%
    - skill4:
      name: AngularJS
      percentage: 60%
    - skill5:
      name: MeteorJS
      percentage: 50%