# Site settings
title: Rishabh Karajgi's CV 
description: karajrish's CV
favicon: /resumecard/assets/img/avatar.jpg
baseurl: ""
url: ""
rss_url: 
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Rishabh Karajgi
  title: Developer and Programmer
  address: Warangal, India
  email: rishabh.karajgi@gmail.com
  link: 
  weibo:
  github: karajrish
  linkedin: rishabh-karajgi-b450036b
  twitter: RishabhKarajgi
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: WSDC, NIT Warangal
      location: Warangal, India
      title: Web Designer and Developer
      started: 2014
      duration: (2014 - 2015)
      description: 
  educationHistory:
    - education1:
      organization: National Institute of Technology, Warangal
      location: Warangal, India
      degree: B.Tech
      major: Computer Science and Engineering
      started: 2013
      duration: (2013 - 2017)
      description: 
    - education2:
      organization: Indian School Of Business
      location: Hyderabad, India
      degree: Masters
      major: Technology Entrepreneurship
      started: 2015
      duration: (2015 - 2017)
      description:
  languages:
    - language1:
      name: Marathi
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML/CSS
      percentage: 100%
    - skill2:
      name: JavaScript
      percentage: 70%
    - skill3:
      name: C/C++
      percentage: 70%
    - skill4:
      name: Python
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
